services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      NODE_ENV: development
      APP_PORT: ${APP_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./app:/app # mount the local app directory to the app directory in the container
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: